import type { ChordSheet } from "@/lib/chords/types";

export interface PdfOptions {
  title?: string;
  includeChords?: boolean;
  includeFingerings?: boolean;
  pageSize?: "A4" | "Letter";
}

export function generatePdfHtml(sheet: ChordSheet, options?: PdfOptions): string {
  const opts = { includeChords: true, includeFingerings: true, pageSize: "A4" as const, ...options };

  return `<!DOCTYPE html>
<html>
<head>
  <style>
    @page { size: ${opts.pageSize}; margin: 2cm; }
    body { font-family: 'Georgia', serif; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 20px; }
    .meta { font-size: 12px; color: #888; margin-bottom: 20px; }
    .chord { font-weight: bold; font-size: 13px; color: #b45309; font-family: 'Courier New', monospace; }
    .chord-line { margin-bottom: 4px; }
    .lyric-line { margin-bottom: 16px; }
    .section-label { font-style: italic; color: #666; margin-top: 16px; margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 6px 8px; text-align: left; border-bottom: 1px solid #eee; font-size: 12px; }
    .footer { margin-top: 40px; font-size: 10px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <h1>${escapeHtml(sheet.title)}</h1>
  ${sheet.artist ? `<div class="subtitle">${escapeHtml(sheet.artist)}</div>` : ""}
  <div class="meta">Key: ${sheet.progression.key} | Tempo: ${sheet.progression.tempo} bpm | Time: ${sheet.progression.timeSignature[0]}/${sheet.progression.timeSignature[1]}</div>
  <hr>
  <div class="chord-line">
    ${sheet.progression.chords.map((c) => {
      const { chordToString } = require("@/lib/chords/database");
      return `<span class="chord">${chordToString(c)}</span>`;
    }).join(" ")}
  </div>
  <div class="footer">Generated by Chord Weaver</div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export async function generatePdfBuffer(sheet: ChordSheet, options?: PdfOptions): Promise<Buffer> {
  const html = generatePdfHtml(sheet, options);

  if (typeof window === "undefined") {
    const { default: playwright } = await import("playwright");
    const browser = await playwright.chromium.launch();
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });
    const pdfBuffer = await page.pdf({ format: options?.pageSize?.toLowerCase() ?? "a4" });
    await browser.close();
    return Buffer.from(pdfBuffer);
  }

  throw new Error("PDF generation is only available server-side");
}
